export const CLIENT_PATHS = {
  main: '/',
  sidebar: '/sidebar',
  vehicle: '/vehicle',
  elements: '/elements',
  architecture: '/architecture',
  suppliers: '/suppliers',
  tickets: '/tickets',
  services: '/services',
  threats: '/threats',
  controls: '/controls',
  documents: '/documents',
  reports: '/reports',
  notifications: '/notifications',
  certification: '/certification',
  feeds: '/feeds',
  configurations: '/configurations',
  settings: '/settings',
  login: '/login',
  security: '/sidebar/security',
};

export const API_PATHS = {
  users: '/users',
  gatewayForVehicle: '/gatewayForVehicle',
  gateways: '/gateways',
  domains: '/domains',
  ecus: '/ecus',
  login: '/login',
  vehicles: '/vehicles',
  functions: '/functions',
  data: '/data',
  tickets: '/tickets',
  conceptThreats: '/threats',
  threats: '/threats',
  threatsOem: '/threatsOem',
  controlGroupsOem: '/controlGroupsOem',
  controls: '/controls',
  controlGroups: '/groups',
  brands: '/brands',
  suppliers: '/suppliers',
  securityConcepts: '/securityConcepts',
  controlThreats: '/controlThreats',
  tests: '/penetrationTests',
  mainFindings: '/mainFindings',
  detailedFindings: '/detailedFindings',
  securityRequirements: '/securityRequirements',
  vehicleScheme: '/vehicleScheme',
  feeds: '/alertFeeds',
  alerts: '/alerts',
  ecusForVehicle: '/ecusForVehicle',
};
